# To trigger pipeline push a new tag

on:
  push:
    tags:
      - '*'

jobs:
  docker_push:
    runs-on: ubuntu-22.04
    name: Deploy Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Images
        run: make docker.all -e HUB=${{ github.repository }} -e TAG=${{ env.TAG }}
      - name: Push Operator
        run: docker push ghcr.io/${{ github.repository }}/operator:${{ env.TAG }}
      - name: Push Ext Authz
        run: docker push ghcr.io/${{ github.repository }}/ext-authz:${{ env.TAG }}
      - name: Push Istioctl
        run: docker push ghcr.io/${{ github.repository }}/istioctl:${{ env.TAG }}
      - name: Push App
        run: docker push ghcr.io/${{ github.repository }}/app:${{ env.TAG }}
      - name: Push Ztunnel
        run: docker push ghcr.io/${{ github.repository }}/ztunnel:${{ env.TAG }}
      - name: Push Install CNI
        run: docker push ghcr.io/${{ github.repository }}/install-cni:${{ env.TAG }}
      - name: Push Proxy V2
        run: docker push ghcr.io/${{ github.repository }}/proxyv2:${{ env.TAG }}
      - name: Push Pilot
        run: docker push ghcr.io/${{ github.repository }}/pilot:${{ env.TAG }}
